-- MySQL Script generated by MySQL Workbench
-- Mon Sep 28 12:08:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loovies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loovies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loovies` DEFAULT CHARACTER SET utf8 ;
USE `loovies` ;

-- -----------------------------------------------------
-- Table `loovies`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loovies`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loovies`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loovies`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(125) NULL,
  `text` LONGTEXT NULL,
  `img` VARCHAR(45) NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idpost`, `user_idUser`),
  UNIQUE INDEX `idpost_UNIQUE` (`idpost` ASC) VISIBLE,
  INDEX `fk_post_user_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `loovies`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loovies`.`customize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loovies`.`customize` (
  `idcustomize` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `copyright` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomize`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loovies`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loovies`.`media` (
  `idmedia` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `format` VARCHAR(45) NULL,
  `mediacol` VARCHAR(45) NULL,
  `post_idpost` INT NOT NULL,
  `post_user_idUser` INT NOT NULL,
  `customize_idcustomize` INT NOT NULL,
  PRIMARY KEY (`idmedia`, `post_idpost`, `post_user_idUser`, `customize_idcustomize`),
  UNIQUE INDEX `idmedia_UNIQUE` (`idmedia` ASC) VISIBLE,
  INDEX `fk_media_post1_idx` (`post_idpost` ASC, `post_user_idUser` ASC) VISIBLE,
  INDEX `fk_media_customize1_idx` (`customize_idcustomize` ASC) VISIBLE,
  CONSTRAINT `fk_media_post1`
    FOREIGN KEY (`post_idpost` , `post_user_idUser`)
    REFERENCES `loovies`.`post` (`idpost` , `user_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_customize1`
    FOREIGN KEY (`customize_idcustomize`)
    REFERENCES `loovies`.`customize` (`idcustomize`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loovies`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loovies`.`categorie` (
  `idcategorie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorie`),
  UNIQUE INDEX `idcategorie_UNIQUE` (`idcategorie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loovies`.`post_has_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loovies`.`post_has_categorie` (
  `post_idpost` INT NOT NULL,
  `post_user_idUser` INT NOT NULL,
  `categorie_idcategorie` INT NOT NULL,
  PRIMARY KEY (`post_idpost`, `post_user_idUser`, `categorie_idcategorie`),
  INDEX `fk_post_has_categorie_categorie1_idx` (`categorie_idcategorie` ASC) VISIBLE,
  INDEX `fk_post_has_categorie_post1_idx` (`post_idpost` ASC, `post_user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_categorie_post1`
    FOREIGN KEY (`post_idpost` , `post_user_idUser`)
    REFERENCES `loovies`.`post` (`idpost` , `user_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_categorie_categorie1`
    FOREIGN KEY (`categorie_idcategorie`)
    REFERENCES `loovies`.`categorie` (`idcategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
